bcgov/EDUC-GRAD-ALGORITHM-API

- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/EducGradAlgorithmTestBase.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/controller/GradAlgorithmControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmServiceTests.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/service/GradRuleProcessorServiceTests.java
Added Controller tests to reach 80% coverage
> Controller Test

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/GradCommonConfig.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradAlgorithmAPIConstants.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/LogHelper.java
- api/src/main/resources/application.yaml
- api/src/test/resources/application.yaml
- tools/openshift/api.dc.yaml
Splunk logging is initially implemented.
> Splunk logging is initially implemented.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAssessmentService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradCourseService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradGraduationStatusService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradProgramService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradRuleProcessorService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradSchoolService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradStudentService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/StudentGraduationService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/ThreadLocalStateUtil.java
correlationID is delegated to the downstream api calls.
> correlationID is delegated to the downstream api calls.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-1617: the issue has been resolved.
> GRAD2-1617: the issue has been resolved.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/dto/GraduationProgramCode.java
GRAD2-1614 : removed assessmentReleaseDate.
> GRAD2-1614 : removed assessmentReleaseDate.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> GRAD2-1703

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/dto/GraduationData.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
Add Lastest Session Date to student "CLOB"
> GRAD2-1770

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-1771 : the task is complete
> GRAD2-1771 : the task is complete

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-1771 : enhanced the grad message appearance.
> GRAD2-1771 : enhanced the grad message appearance.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-1576 - New Program 1986-PF changes
> GRAD2-1576 - New Program 1986-PF changes

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/dto/StudentCoursesComparator.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/APIUtils.java
GRAD2-1799 - Sorting on COURSE LEVEL needs to remove any letters from the level before sorting
> GRAD2-1799 - Sorting on COURSE LEVEL

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> GRADT-584 : bug fix is done.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRADT-584 : the issue has been resolved for 2 periods on projected grad message.
> GRADT-584 : the issue has been resolved for 2 periods.

- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- Dockerfile
- api/src/main/resources/application.yaml
- tools/openshift/api.dc.yaml
Grad2-1947 Grad Algorithm API Resource Optimization
> Resource Optimization

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RestWebClient.java
Grad Algorithm API refactoring is done.
> Grad2-1929 Refactoring/Linting

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-1871 - When Adult (1950) students have no eligible courses their Non Grad reasons are wonky
> GRAD2-1871 - When Adult (1950) students have no eligible courses

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradAlgorithmApiUtils.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmServiceTests.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/util/GradAlgorithmApiUtilsTests.java
GRAD2-1863 - Sort order for Adult Grads needs to take into consideration highest final LG/%'s when choosing which course meets a requirement
> GRAD2-1863 - Sort order for Adult Grads

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-2128 - HD-19762 New sort for the Adult Graduation Algorithm, add Course Level
> GRAD2-2128 - HD-19762 New sort for the Adult Graduation Algorithm, add Course Level

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-2142: fixed the grad date for a graduated student in TVR.
> GRAD2-2142: fixed the grad date for a graduated student in TVR.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/dto/GradAlgorithmGraduationStudentRecord.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/DateUtils.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradLocalDateDeserializer.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradLocalDateSerializer.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/JsonTransformer.java
GRAD2-2024: resolved the issue.
> GRAD2-2024: resolved the issue.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/controller/GradAlgorithmController.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/controller/GradAlgorithmControllerTest.java
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmServiceTests.java
GRAD2-2325: Hypothetical Grad Algorithm run is implemented.
> GRAD2-2325: Hypothetical Grad Algorithm run is implemented.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> GRAD2-2193: task is complete.

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> Grad release 1.10.0

- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/create_tag.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- .github/workflows/on.pr.yml
- tools/config/update-configmap.sh
> Sync from main

- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- api/pom.xml
> Grad release

- .github/workflows/build.from.developer.branch.deploy.to.dev.yml
- .github/workflows/build.from.main.branch.deploy.to.dev.yml
- .github/workflows/build.from.release.branch.deploy.to.dev.yml
- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_test.yml
- tools/openshift/api.dc.yaml
Updated to Deployment objects from DesploymentConfig
> GRAD2-3103

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/dto/School.java
GRAD2-2761: districtId is newly added into School Clob.
> GRAD2-2761: districtId is newly added into School Clob.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
- api/src/test/resources/json/gradstatus_studentrecord.json
- api/src/test/resources/json/gradstatus_studentrecord_1950.json
GRAD2-3036: the issue with null schoolAtGradId after graduation is fixed.
> GRAD2-3036: the issue with null schoolAtGradId after graduation is fixed.

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
GRAD2-3263 - graduation algorithm overwriting school at graduation for SCCP students
> GRAD2-3263 - graduation algorithm overwriting school at graduation for SCCP students

- tools/openshift/api.dc.yaml
GRAD2-3307 - Remove reference to api-student-graduation-db-secret from deployment file
> GRAD2-3307 - Remove reference to api-student-graduation-db-secret from deployment file

- api/pom.xml
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/WebSecurityConfiguration.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/controller/APIMetadataController.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradRuleProcessorService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradAlgorithmAPIConstants.java
- api/src/main/resources/application.yaml
- api/src/test/java/ca/bc/gov/educ/api/gradalgorithm/service/GradRuleProcessorServiceTests.java
- api/src/test/resources/application.yaml
- tools/config/update-configmap.sh
GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs
> GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RequestInterceptor.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/config/RestWebClient.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAssessmentService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradCourseService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradGraduationStatusService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradRuleProcessorService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradStudentService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/caching/GradProgramService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/caching/GradSchoolService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/caching/StudentGraduationService.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/GradAlgorithmAPIConstants.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/JwtUtil.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/LogHelper.java
- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/util/ThreadLocalStateUtil.java
> Grad2-3284 Set Request Headers

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> Grad2-2674

- api/src/main/java/ca/bc/gov/educ/api/gradalgorithm/service/GradAlgorithmService.java
> completiondate is set to new date
